config/routes.rb
RailsPlotwattApp::Application.routes.draw do

  resources :measurements

  resources :posts

end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  # This line below was intended to plug a security vulnerability, but I got errors:
  #RuntimeError: `attr_accessible` is extracted out of Rails into a gem. Please use new recommended protection model for params(strong_parameters) or add `protected_attributes` to your Gemfile to use old one.
  #attr_accessible :title, :content

  validates :title, :content, :presence => true
  validates :title, :length => { :minimum => 2 }
  validates :title, :uniqueness => { :message => "title taken" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  before_action :set_measurement, only: [:show, :edit, :update, :destroy]

  # GET /measurements
  # GET /measurements.json
  def index
    @measurements = Measurement.all
  end

  # GET /measurements/1
  # GET /measurements/1.json
  def show
  end

  # GET /measurements/new
  def new
    @measurement = Measurement.new
  end

  # GET /measurements/1/edit
  def edit
  end

  # POST /measurements
  # POST /measurements.json
  def create
    @measurement = Measurement.new(measurement_params)

    respond_to do |format|
      if @measurement.save
        format.html { redirect_to @measurement, notice: 'Measurement was successfully created.' }
        format.json { render action: 'show', status: :created, location: @measurement }
      else
        format.html { render action: 'new' }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measurements/1
  # PATCH/PUT /measurements/1.json
  def update
    respond_to do |format|
      if @measurement.update(measurement_params)
        format.html { redirect_to @measurement, notice: 'Measurement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measurements/1
  # DELETE /measurements/1.json
  def destroy
    @measurement.destroy
    respond_to do |format|
      format.html { redirect_to measurements_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measurement
      @measurement = Measurement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measurement_params
      params.require(:measurement).permit(:AlwaysOn, :HeatingAC, :Refrigeration, :Dryer, :Cooking, :Other, :DatetimeMidpoint)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end
  
  # GET /posts/1
  # GET /posts/1.json
  def show
    #@post = Post.find(params[:id])  
  end
  
  # GET /posts/new
  def new
    @post = Post.new
  end
  
  # GET /posts/1/edit
  def edit
    #@post = Post.find(params[:id])  
  end
  
  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Plotwatt App</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <p><%= value %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/measurements/_form.html.erb
<%= form_for(@measurement) do |f| %>
  <% if @measurement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@measurement.errors.count, "error") %> prohibited this measurement from being saved:</h2>

      <ul>
      <% @measurement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :AlwaysOn %><br>
    <%= f.text_field :AlwaysOn %>
  </div>
  <div class="field">
    <%= f.label :HeatingAC %><br>
    <%= f.text_field :HeatingAC %>
  </div>
  <div class="field">
    <%= f.label :Refrigeration %><br>
    <%= f.text_field :Refrigeration %>
  </div>
  <div class="field">
    <%= f.label :Dryer %><br>
    <%= f.text_field :Dryer %>
  </div>
  <div class="field">
    <%= f.label :Cooking %><br>
    <%= f.text_field :Cooking %>
  </div>
  <div class="field">
    <%= f.label :Other %><br>
    <%= f.text_field :Other %>
  </div>
  <div class="field">
    <%= f.label :DatetimeMidpoint %><br>
    <%= f.datetime_select :DatetimeMidpoint %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/measurements/edit.html.erb
<h1>Editing measurement</h1>

<%= render 'form' %>

<%= link_to 'Show', @measurement %> |
<%= link_to 'Back', measurements_path %>

app/views/measurements/index.html.erb
<h1>Listing measurements</h1>

<table>
  <thead>
    <tr>
      <th>Alwayson</th>
      <th>Heatingac</th>
      <th>Refrigeration</th>
      <th>Dryer</th>
      <th>Cooking</th>
      <th>Other</th>
      <th>Datetimemidpoint</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @measurements.each do |measurement| %>
      <tr>
        <td><%= measurement.AlwaysOn %></td>
        <td><%= measurement.HeatingAC %></td>
        <td><%= measurement.Refrigeration %></td>
        <td><%= measurement.Dryer %></td>
        <td><%= measurement.Cooking %></td>
        <td><%= measurement.Other %></td>
        <td><%= measurement.DatetimeMidpoint %></td>
        <td><%= link_to 'Show', measurement %></td>
        <td><%= link_to 'Edit', edit_measurement_path(measurement) %></td>
        <td><%= link_to 'Destroy', measurement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Measurement', new_measurement_path %>

app/views/measurements/new.html.erb
<h1>New measurement</h1>

<%= render 'form' %>

<%= link_to 'Back', measurements_path %>

app/views/measurements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Alwayson:</strong>
  <%= @measurement.AlwaysOn %>
</p>

<p>
  <strong>Heatingac:</strong>
  <%= @measurement.HeatingAC %>
</p>

<p>
  <strong>Refrigeration:</strong>
  <%= @measurement.Refrigeration %>
</p>

<p>
  <strong>Dryer:</strong>
  <%= @measurement.Dryer %>
</p>

<p>
  <strong>Cooking:</strong>
  <%= @measurement.Cooking %>
</p>

<p>
  <strong>Other:</strong>
  <%= @measurement.Other %>
</p>

<p>
  <strong>Datetimemidpoint:</strong>
  <%= @measurement.DatetimeMidpoint %>
</p>

<%= link_to 'Edit', edit_measurement_path(@measurement) %> |
<%= link_to 'Back', measurements_path %>

app/views/posts/edit.html.erb
<h1>Edit Post </h1>

<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <h2>Errors:</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>      
      <% end %>
    </ul>
  <% end %>
  
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit "Update post!" %><br />
  </p>
<% end %>

app/views/posts/index.html.erb
<h1>Rails Plotwatt App</h1>

<% @posts.each do |post| %>
  <h2><%= link_to(post.title, post) %></h2>
  <p><%= post.content %></p>
  <p>
    <%= link_to "Edit", edit_post_path(post) %> |
    <%= link_to "Delete", post, :confirm => "Are you sure?", :method => :delete %>
  </p>  
  <hr />
<% end %>

<p><%= link_to("Add a new post", new_post_path) %></p>

app/views/posts/new.html.erb
<h1>Add a new Post</h1>

<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <h2>Errors:</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>      
      <% end %>
    </ul>
  <% end %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>  
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit "Add a new post!" %><br />
  </p>    
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>
<small><%= @post.created_at %></small>